sequential:
    script:
        - rm -rf /srv/backend/
        - mkdir /srv/backend/
        - cp -R * /srv/backend/
        - source /srv/SurveyBackendEnv/bin/activate
        - export FLASK_ENV=production
        - flask run
