sequential:
    script:
        - kill $(pgrep -f flask) || echo "no flask server running"
        - rm -rf /srv/backend/
        - mkdir /srv/backend/
        - cp -R * /srv/backend/
        - bash /srv/backend/production_start.sh
        - sudo systemctl restart nginx
        - sudo systemctl start SurveyBackend